---
- hosts: all
  become: true

  tasks:
   - name: Set timezone to Europe/Londo
     timezone:
      name: Europe/London

   - name: updates server
     apt: update_cache=yes

   - name: upgrade a server
     apt: upgrade=dist

   - name: remove old packages that are not needed
     apt:
      autoremove: true

   - name: purge config file left by old packages
     apt:
      purge: true

   - name: Start service ufw
     command: ufw --force enable

   - name: Disable ipv6
     lineinfile:
      path: /etc/default/ufw
      regexp: '^IPV6=yes'
      line: IPV6=no
      backrefs: true

   - name: Allow access to port 22 for ssh
     ufw:
      rule: allow
      port: '22'

   - name: Restart ufw
     service:
      name: ufw
      state: restarted
