---                                                                             
                                                                                 
- hosts: dev                                                                    
  become: true                                                                  
                                                                                 
  pre_tasks:                                                                    
   - name: Set timezone to Europe/London                                        
     timezone:                                                                  
      name: Europe/London                                                       
                                                                                 
   - include_role:                                                              
       name: updateos   