---                                                                             
                                                                                 
- hosts: localhost                                                                    
  become: true                                                                  
                                                                                 
  pre_tasks:                                                                                                                
 
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

  roles:
    - timezone
    - updateos
    - firewall
    - os_hardening                                                                             