---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "ubuntu:latest"
    command: ""
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
