---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  PATH=${PATH}
  yamllint .
  ansible-lint .
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd" 
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
